"""Common utilities for AgentSH."""

from agentsh.utils.async_utils import (
    AsyncCache,
    AsyncTimeoutError,
    Debouncer,
    RateLimiter,
    RetryResult,
    Throttler,
    cancel_all,
    first_completed,
    gather_with_limit,
    rate_limited,
    retry,
    run_in_executor,
    run_with_timeout,
    safe_cancel,
    timeout,
    with_retry,
)
from agentsh.utils.env import get_env, get_env_bool, get_env_int, get_env_or_fail
from agentsh.utils.ux import (
    Color,
    ErrorContext,
    ErrorFormatter,
    OutputBuffer,
    ProgressBar,
    Spinner,
    SpinnerStyle,
    Table,
    TableColumn,
    colorize,
    get_error_suggestion,
    print_error,
    print_info,
    print_success,
    print_warning,
    status,
    strip_ansi,
)
from agentsh.utils.crypto import (
    EncryptedData,
    EncryptionAlgorithm,
    EncryptionError,
    Encryptor,
    KeyDerivationError,
    SecureStore,
    generate_key,
    generate_key_from_password,
    generate_token,
    hash_secret,
    secure_compare,
    verify_secret,
)
from agentsh.utils.markdown import (
    MarkdownRenderer,
    MarkdownStyle,
    RenderConfig,
    get_markdown_renderer,
    render_markdown,
    strip_markdown,
)
from agentsh.utils.validators import (
    CommandValidator,
    InputSanitizer,
    PathValidator,
    ValidationError,
    ValidationResult,
    redact_secrets,
    validate_and_sanitize,
)
from agentsh.utils.resource_manager import (
    CleanupHandler,
    ResourceLimits,
    ResourceManager,
    ResourceStatus,
    ResourceType,
    ResourceUsage,
    cleanup_on_exhaustion,
    get_resource_manager,
    register_cleanup,
    resource_guard,
)
from agentsh.utils.syntax import (
    AnsiColor,
    ColorScheme,
    DARK_SCHEME,
    LIGHT_SCHEME,
    LanguageDefinition,
    LANGUAGES,
    PYTHON,
    JAVASCRIPT,
    BASH,
    SyntaxHighlighter,
    TokenType,
    get_highlighter,
    highlight,
    highlight_file,
)

__all__ = [
    # Async utilities
    "AsyncCache",
    "AsyncTimeoutError",
    "Debouncer",
    "RateLimiter",
    "RetryResult",
    "Throttler",
    "cancel_all",
    "first_completed",
    "gather_with_limit",
    "rate_limited",
    "retry",
    "run_in_executor",
    "run_with_timeout",
    "safe_cancel",
    "timeout",
    "with_retry",
    # Environment
    "get_env",
    "get_env_bool",
    "get_env_int",
    "get_env_or_fail",
    # UX
    "Color",
    "ErrorContext",
    "ErrorFormatter",
    "OutputBuffer",
    "ProgressBar",
    "Spinner",
    "SpinnerStyle",
    "Table",
    "TableColumn",
    "colorize",
    "get_error_suggestion",
    "print_error",
    "print_info",
    "print_success",
    "print_warning",
    "status",
    "strip_ansi",
    # Crypto
    "EncryptedData",
    "EncryptionAlgorithm",
    "EncryptionError",
    "Encryptor",
    "KeyDerivationError",
    "SecureStore",
    "generate_key",
    "generate_key_from_password",
    "generate_token",
    "hash_secret",
    "secure_compare",
    "verify_secret",
    # Markdown
    "MarkdownRenderer",
    "MarkdownStyle",
    "RenderConfig",
    "get_markdown_renderer",
    "render_markdown",
    "strip_markdown",
    # Validators
    "CommandValidator",
    "InputSanitizer",
    "PathValidator",
    "ValidationError",
    "ValidationResult",
    "redact_secrets",
    "validate_and_sanitize",
    # Resource Management
    "CleanupHandler",
    "ResourceLimits",
    "ResourceManager",
    "ResourceStatus",
    "ResourceType",
    "ResourceUsage",
    "cleanup_on_exhaustion",
    "get_resource_manager",
    "register_cleanup",
    "resource_guard",
    # Syntax highlighting
    "AnsiColor",
    "ColorScheme",
    "DARK_SCHEME",
    "LIGHT_SCHEME",
    "LanguageDefinition",
    "LANGUAGES",
    "PYTHON",
    "JAVASCRIPT",
    "BASH",
    "SyntaxHighlighter",
    "TokenType",
    "get_highlighter",
    "highlight",
    "highlight_file",
]
